commonfields:
  id: IP Threat Enrichment Playbook
  version: -1
name: IP Threat Enrichment Playbook
description: |
  This playbook performs IP threat enrichment using a custom integration.
  It validates the input, calls the enrichment script, and stores the results.

type: playbook
tags: [Enrichment, Threat Intelligence]
inputs:
  - key: IPAddress
    value: {}
    required: true
    description: "IP address to enrich"

tasks:
  "1":
    id: 1
    task:
      id: 1
      version: -1
      name: Validate IP Address
      type: regular
      script: Builtin|||IsIPValid
      scriptarguments:
        value:
          simple: ${inputs.IPAddress}
      type: condition
    nexttasks:
      "#default#": [99]  # Exit playbook if invalid
      "yes": [2]

  "2":
    id: 2
    task:
      id: 2
      version: -1
      name: Enrich IP via Custom Integration
      type: regular
      script: IPThreatEnrichment|||ip-enrich
      scriptarguments:
        ip:
          simple: ${inputs.IPAddress}
    nexttasks:
      "": [3]

  "3":
    id: 3
    task:
      id: 3
      version: -1
      name: Save Enrichment Results
      type: regular
      script: Builtin|||SaveResults
      scriptarguments:
        results:
          simple: ${lastCompletedTask}
    nexttasks:
      "": []

  "99":
    id: 99
    task:
      id: 99
      version: -1
      name: Exit: Invalid IP
      type: title
    nexttasks:
      "": []